### ISSUE TITLE
Objetivos

### ISSUE THREAD

**Issue by YadhiraEscobedo88** [YadhiraEscobedo88/PROYECTO-INTEGRADOR-DE-CIERRE-DEL-BLOQUE-II-A-PROMEDIAR.#2]

**Comment by cathymendoza** [comment]
![enter image description here](https://images.cooltext.com/5136778.png)

<a href="http://es.cooltext.com" target="_top"><img src="https://cooltext.com/images/ct_button.gif" width="88" height="31" alt="Cool Text: Generador de Logotipos y Gráficos." /></a>


La **realidad virtual** ha revolucionado el mundo en sus diversos ámbitos, más allá de la informática, ya que esta técnica también es ampliamente utilizada en entornos médicos, educativos, espaciales y una larga lista de actividades científicas. Esto ha sido posible, no sólo por el  atractivo que presenta la RV para las personas, sino también por la  enorme cantidad de ventajas y funcionalidades que ofrece esta disciplina.

![](https://i1.wp.com/medialist.info/wp-content/uploads/2018/01/2018_01_26_medialist_VR-Healthcare-e1516986886970.jpg?fit=1200%2C600)

Se intenta lograr que la realidad virtual alcance los objetivos para los cuales fue creada, que básicamente pretende generar un entorno que no pueda ser diferenciado de la realidad física, ya que a través de dicho mundo físico, la realidad virtual lo utiliza para sustituirlo por un ambiente de entrada y salida de información, por intermedio de una computadora.

La idea fundamental, para lo cual fue desarrollada la realidad virtual, ha sido desde siempre lograr la creación de un mundo irreal pero posible, por lo que se lo ha dotado de objetos que poseen relaciones entre ellos y permiten la interacción de las personas en dicho universo irreal.

![](https://www.nmy.de/media/mainteaser/ar_home.jpg)
