### ISSUE TITLE
Historia

### ISSUE THREAD

**Issue by cathymendoza** [YadhiraEscobedo88/PROYECTO-INTEGRADOR-DE-CIERRE-DEL-BLOQUE-II-A-PROMEDIAR.#6]

**Comment by xnggi16** [comment]
El origen de la realidad virtual fue gracias al sistema desarrollado por la compañía Philco Corporation en el año 1958. Este sistema había sido diseñado para lograr la generación de entornos artificiales, a los cuales podían acceder las personas mediante la utilización de un dispositivo visual en forma de casco, que podía ser controlado a través de los movimientos que los usuarios realizaban con sus cabezas.



A finales de la década de los sesenta, y debido al apoyo que recibieron las investigaciones avocadas al campo de la realidad virtual de parte de la NASA, comenzaron a crearse los ambientes interactivos, los cuales ofrecían la posibilidad de que los usuarios pudieran participar del entorno virtual con todo su cuerpo.

Poco tiempo después, los avances en esta área lograron incorporar un sin fin de alternativas que mejoraban la experiencia en el uso de la realidad virtual, tales como la posibilidad de mover objetos gráficos, crear entornos tridimensionales y estereoscópicos y permitir la interacción entre diversas personas.

![enter image description here](https://media.giphy.com/media/Vp4cpDCA4Pwm4/giphy.gif)
